# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

parameters:
- name: apply
  displayName: "Terraform Apply"
  type: bool
  default: false


jobs:
  - job: 'terraformExecution'
    pool:
      name: szecsikr
    steps:
    - bash: |
        terraform init
      displayName: Terraform Init
    - bash: |
        terraform validate
      displayName: Terraform Validate
    - bash: |
        terraform plan
      displayName: Terraform Plan
