# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

parameters:
  - name: runTerraformApply
    displayName: "Run Terraform Apply"
    type: boolean
    default: false

stages:
- stage: "TerraformPlan"
  displayName: Terraform Plan
  jobs:
    - job: 'terraformExecution'
      pool:
        name: szecsikr
      steps:
      - bash: |
          terraform init
        displayName: Terraform Init
      - bash: |
          terraform validate
        displayName: Terraform Validate
      - bash: |
          terraform plan
        displayName: Terraform Plan
- stage: "TerraformApply"
  displayName: Terraform Apply
  dependsOn: TerraformPlan
  condition: and(succeeded(), eq(variables['parameters.runTerraformApply'], 'true'))
  jobs:
    - job: 'terraformExecution'
      pool:
        name: szecsikr
      steps:
      - bash: |
          terraform init
        displayName: Terraform Init
      - bash: |
          terraform plan
        displayName: Terraform Plan
