# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
jobs:
  - job: 'Terraform Execution'
    pool:
      name: szecsikr
    steps:
    - displayName: 'Terraform init'
      script: |
        terraform init
    - displayName: Validate Terraform
      script: |
        terraform validate
    - displayName: Plan
      script: |
        terraform plan