# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
jobs:
  - job: 'Terraform Execution'
    pool:
      name: szecsikr
    steps:
    - task: HashiCorpTerraformInstaller@0  # Task to install Terraform (if not available)
      inputs:
        terraformVersion: 'latest'  # Specify version if needed
    - script: |
        terraform init
      displayName: 'Terraform init'
    - script: |
        terraform validate
      displayName: 'Validate Terraform'
    - script: |
        terraform plan
      displayName: 'Terraform Plan'